version: '3'
services:
  webapp:
    volumes: 
    - ./vitaes-webapp/src:/project/src
    build: vitaes-webapp/.
    image: vitaes/webapp
  server:
    build: vitaes-renderer/.
    image: vitaes/server
    ports:
    - "5000:5000"
  renderer:
    build: vitaes-renderer/.
    command: python3 Consumer.py
    image: vitaes/renderer
    depends_on:
    - rabbitmq
  nginx:
    build: vitaes-nginx/.
    ports:
    - "443:443"
  nginx-http:
    build: vitaes-nginx-http/.
    ports:
    - "80:80"
  rabbitmq:
    image: rabbitmq:alpine
  redis:
    image: redis
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: vitaes
    volumes:
    - ./db:/data/db
  mongo-express:
    image: mongo-express
    restart: always
    ports:
    - 8081:8081
    depends_on:
    - mongo 
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: vitaes
