name: webapp

on:
  push:
    branches: [ master ]
    paths:
    - 'webapp/**'
  pull_request:
    paths:
    - 'webapp/**'
  release:
    paths:
    - 'webapp/**'

env:
  IMAGE_NAME: vitaes/webapp

defaults:
  run:
    working-directory: ./webapp

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 11.14
      uses: actions/setup-node@v1
      with:
        node-version: 11.14
    - run: yarn
    - run: yarn build
    - run: yarn test
    - run: echo ${{ github.ref }}
  push:
    needs: build
    if: contains(github.ref, 'release')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build image
      run: |
        VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
        [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
        echo "::set-env name=VERSION::$VERSION"
        docker build -t $IMAGE_NAME:latest .
        docker tag $IMAGE_NAME:latest $IMAGE_NAME:$VERSION
    - name: Login to Docker hub
      run: |
        echo ${{ secrets.DOCKER_HUB_PASSWORD }} | \
        docker login -u ${{ secrets.DOCKER_HUB_USER }} --password-stdin
    - name: Push image
      run: |
        docker push $IMAGE_NAME:latest
        docker push $IMAGE_NAME:$VERSION
    - name: Logout from Docker hub
      run: docker logout
  deploy:
    needs: push
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
    - name: Setup kubeconfig
      run: doctl kubernetes cluster kubeconfig save vitaes
    - name: Rollout new container
      run: kubectl set image deployment/webapp webapp=$IMAGE_NAME:$VERSION
